  version: '3'
  services:
    web:
      # "build: ."" cannot be used because Dockerfile.dev (for development) instead of just Dockerfile (for production)
      build:
        context: .
        dockerfile: Dockerfile.dev
      ports: 
        - "3000:3000"
      volumes:
        # Do not map a folder against /app/node_modules
        - /app/node_modules
        # Map current local directory against app folder in container
        - .:/app
    tests:
      build:
        context: .
        dockerfile: Dockerfile.dev
      volumes: 
        - /app/node_modules
        - .:/app
      # Overwrite the default command of Dockerfile
      command: ["npm","run","test"]